FROM node:latest

# Linux Command
RUN apt update
RUN apt install vim -y
RUN apt install inetutils-ping -y 
RUN apt install net-tools -y

# Set working direction

WORKDIR /app

# Entry point

CMD ["/bin/sh"]




